[package]
name = "semdesk"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "semdesk"
path = "src/main.rs"


[dependencies]
pdf-extract = "0.6.4"
rand = "0.8.3"
sha256 = "1.1.2"
faiss = "0.12.0"
tch = "0.10.1"
rust-bert = "0.20.0"
ndarray = "0.14.0"
ndarray-linalg = "0.14.0"
